/*
 * ActivitiesSubGUI.java
 *
 * Created on 1. Januar 2006, 23:25
 */

package pzm.subgui;

import pzm.dbcon.DB_projektzeit_Connect;
import pzm.core.Activity;
import java.sql.*;
/**
 *
 * @author  hertel
 *
 * Formular zum Erstellen, Ändern und Löschen von Tätigkeiten
 * wird aufgerufen von ActivitiesWindow
 */
public class ActivitiesSubGUI extends javax.swing.JFrame {
    
    private static int status;              //0=Neu; 1=Bearbeiten
    private static String activityName;     
    private static int activityID;      
    private Activity activity;          
    private Connection con;             
    private int projID = -1;                
    private int projGrID = -1;
    
    /** Creates new form ActivitiesSubGUI */
    public ActivitiesSubGUI(int status, String activityName,  int activityID) {
        this.status = status;
        this.activityName = activityName;
        this.activityID = activityID;
        initComponents();
        if(status == 0) {
            //Neue Tätigkeit soll angelegt werden
            newActivityInit();
        }
        if(status == 1) {
            //Tätigkeit soll bearbeitet werden
            editActivityInit();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelActivity = new javax.swing.JLabel();
        jTextFieldActivity = new javax.swing.JTextField();
        jButtonSaveAndExit = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stammdaten - Tätigkeit bearbeiten");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelActivity.setText("Tätigkeit");
        getContentPane().add(jLabelActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, -1));
        getContentPane().add(jTextFieldActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 220, -1));

        jButtonSaveAndExit.setText("Speichern und schliessen");
        jButtonSaveAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSaveAndExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, -1));
        getContentPane().add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 270, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndExitActionPerformed
        switch(status) {
            case 0:         // status=0, neue Tätigkeit anlegen
                newActivity();
                setVisible(false);
            case 1:         // status=1, vorhandene Tätigkeit bearbeiten
                editActivity();
                setVisible(false);
            default:
                jLabelError.setForeground(new java.awt.Color(255, 0, 0));
                jLabelError.setText("Fehler bei Ausführung des Befehls!");
        }
    }//GEN-LAST:event_jButtonSaveAndExitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivitiesSubGUI(status,  activityName, activityID).setVisible(true);
            }
        });
    }
    
    /*
     *  initialisiert Bearbeitung der Tätigkeit,
     *  ausgewählte Tätigkeit in ActivitiesWindow wird übernommen
     */
    public void editActivityInit() {
        jTextFieldActivity.setText(activityName);
        
    }

    /*
     *  initialisiert das Eingeben einer neuen Tätigkeit
     */
    public void newActivityInit() {
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setText("Es müssen alle Felder ausgewählt werden");
    }
    
    /*
     *  aufgerufen bei Klick auf jButtonSaveAndExit
     *  speichert geänderte Tätigkeit anstelle der alten Tätigkeit
     *  in der DB, Tabelle: Activity
     *  liefert Fehler bei Leereingabe
     */
    public void editActivity() {
        activityName = jTextFieldActivity.getText();
        if(activityName != "") {
            DB_projektzeit_Connect dbCon = new DB_projektzeit_Connect();
            dbCon.openDB();
            con = dbCon.getCon();
        
            try {
                Statement stmt = con.createStatement();
                String sql = "UPDATE Activity SET Activity='" + activityName + "' WHERE ActivityID=" + activityID;
                    stmt.executeUpdate(sql);
                    stmt.close();
                } catch(Exception e) {
                    System.out.println(e.toString()); 
                    System.exit(1);
                }
                dbCon.closeDB(con);
            }
        else {
            jLabelError.setText("Das Feld Aktivität muss ausgefüllt werden!");
        }
    }
    
    /*
     *  aufgerufen bei Klick auf jButtonSaveAndExit
     *  speichert Tätigkeit in der DB, Tabelle: Activity
     *  liefert Fehler bei Leereingabe
     */
    public void newActivity() {
        activityName = jTextFieldActivity.getText();
        if(activityName != "") {
            DB_projektzeit_Connect dbCon = new DB_projektzeit_Connect();
            dbCon.openDB();
            con = dbCon.getCon();
            try {
                Statement stmt = con.createStatement();
                String sql = "INSERT INTO Activity (Activity) VALUES ('" + activityName + "')";
                stmt.executeUpdate(sql);
                stmt.close();
            } catch(Exception e) {
                System.out.println(e.toString()); 
                System.exit(1);
            }
            dbCon.closeDB(con);
        }
        else {
            jLabelError.setText("Das Feld Aktivität muss ausgefüllt werden!");
        }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveAndExit;
    private javax.swing.JLabel jLabelActivity;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JTextField jTextFieldActivity;
    // End of variables declaration//GEN-END:variables
    
}
