/*
 * ProjectSubGUI.java
 *
 * Created on 17. November 2006, 13:41
 */

package pzm.subgui;

import pzm.dbcon.DB_projektzeit_Connect;
import java.sql.*;
/**
 *
 * @author  hertel
 */
public class ProjectSubGUI extends javax.swing.JFrame {
    
    private static int status;
    private static String projectName;
    private static int projectID;
    private static int prGroupID;
    private static String prGroupName;
    private Connection con;
    String startDate = "";
    String endDate = "";
    /** Creates new form ProjectSubGUI */
    

    public ProjectSubGUI(int status) {
        this.status = status;
        initComponents();
        initjComboDate();
    }

    public ProjectSubGUI(int status, String projectName, int projectID) {
        this.status = status;
        this.projectName = projectName;
        this.projectID = projectID;
        initComponents();
        if(status == 0) {
            //Neues Projekt soll erstellt werden
            newProjectInit();
        }
        if(status == 1) {
            //Bestehendes Projekt soll bearbeitet werden
            editProjectInit();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldProject = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxPrGroup = new javax.swing.JComboBox();
        jLabelError = new javax.swing.JLabel();
        jButtonSaveAndExit = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldCostLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTablePos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBoxProjectIsNotActive = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxStartDay = new javax.swing.JComboBox();
        jComboBoxStartMonth = new javax.swing.JComboBox();
        jComboBoxStartYear = new javax.swing.JComboBox();
        jComboBoxEndDay = new javax.swing.JComboBox();
        jComboBoxEndMonth = new javax.swing.JComboBox();
        jComboBoxEndYear = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stammdaten - Projekt bearbeiten / erstellen");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setLabelFor(jTextFieldProject);
        jLabel1.setText("Projektbezeichnung");

        jLabel2.setLabelFor(jComboBoxPrGroup);
        jLabel2.setText("Projektgruppe");

        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelError.setText("jLabel3");

        jButtonSaveAndExit.setText("Speichern und Schliessen");
        jButtonSaveAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndExitActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Abbrechen");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel3.setLabelFor(jTextFieldCostLocation);
        jLabel3.setText("Kostenstelle");

        jTextFieldTablePos.setToolTipText("Geben Sie hiermit die Position in der Gesamttabelle an. Die posotion beginnt bei jeder Projektgruppe mit 1.");

        jLabel4.setLabelFor(jTextFieldTablePos);
        jLabel4.setText("Tabellenposition");

        jLabel5.setLabelFor(jCheckBoxProjectIsNotActive);
        jLabel5.setText("Projekt deaktivieren");

        jCheckBoxProjectIsNotActive.setToolTipText("Wenn Sie das Projekt deaktivieren, erscheint es nicht mehr in der Hauptübersicht.");
        jCheckBoxProjectIsNotActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProjectIsNotActiveActionPerformed(evt);
            }
        });

        jLabel6.setText("Projektstart");

        jLabel7.setText("Projektende");

        jComboBoxStartDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxStartMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxStartYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxEndDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxEndMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxEndYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jTextFieldCostLocation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBoxProjectIsNotActive)
                        .add(127, 127, 127))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jTextFieldTablePos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(layout.createSequentialGroup()
                                                .add(jComboBoxStartDay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jComboBoxStartMonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jComboBoxStartYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(jComboBoxEndDay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jComboBoxEndMonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jComboBoxEndYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(10, 10, 10)
                                .add(jLabelError, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBoxPrGroup, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(jButtonSaveAndExit)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jButtonCancel))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextFieldProject))
                        .add(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextFieldProject, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 9, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(15, 15, 15)
                        .add(jLabel3))
                    .add(layout.createSequentialGroup()
                        .add(jComboBoxPrGroup, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(7, 7, 7)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextFieldCostLocation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5)
                            .add(jCheckBoxProjectIsNotActive))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jTextFieldTablePos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel4))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel6)
                                    .add(jComboBoxStartDay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jComboBoxStartMonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jComboBoxStartYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel7)
                                    .add(jComboBoxEndDay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jComboBoxEndMonth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jComboBoxEndYear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createSequentialGroup()
                                .add(29, 29, 29)
                                .add(jLabelError, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonSaveAndExit)
                    .add(jButtonCancel))
                .add(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndExitActionPerformed
       if (isDateSet()){
        switch(status) {
            case 0:
                saveNewProject();
                setVisible(false);
                dispose();
                break;
            case 1:
                saveProject();
                setVisible(false);
                dispose();
                break;
            default:
                jLabelError.setText("Fehler beim Speichern der Daten!");
        }
       }
    }//GEN-LAST:event_jButtonSaveAndExitActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        setVisible(false);
        dispose();
}//GEN-LAST:event_jButtonCancelActionPerformed

    private void jCheckBoxProjectIsNotActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProjectIsNotActiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxProjectIsNotActiveActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectSubGUI(status, projectName, projectID).setVisible(true);
            }
        });
    }
     public void initjComboDate() {
        jComboBoxEndDay.removeAllItems();
        jComboBoxEndMonth.removeAllItems();
        jComboBoxEndYear.removeAllItems();
        jComboBoxStartDay.removeAllItems();
        jComboBoxStartMonth.removeAllItems();
        jComboBoxStartYear.removeAllItems();
         
         
        int[] year = new int[1101];
        int j = 0;
        
        String[] month = {"Januar", "Februar", "März", "April", "Mai", "Juni",
                          "Juli", "August", "September", "Oktober", "November", 
                          "Dezember"};
        int[] day = new int[31];
        
 
        // ComboBox Year füllen
        jComboBoxStartYear.addItem("<Bitte wählen>");
        jComboBoxEndYear.addItem("<Bitte wählen>");
        for(int i=2000; i<=2050; i++) {
            year[j] = i;
             jComboBoxStartYear.addItem(year[j]);
             jComboBoxEndYear.addItem(year[j]);
            j++;
        }
  
        
        // ComboBox Month füllen
        jComboBoxStartMonth.addItem("<Bitte wählen>");
        jComboBoxEndMonth.addItem("<Bitte wählen>");
        for(int i=0;i<month.length;i++) {
            jComboBoxStartMonth.addItem(month[i]);
            jComboBoxEndMonth.addItem(month[i]);
        }
        // ComboBox Day füllen
        for(int i=0; i<=30; i++) {
            day[i] = i+1;
        }
        jComboBoxStartDay.addItem("<Bitte wählen>");
        jComboBoxEndDay.addItem("<Bitte wählen>");
        for(int i=0;i<day.length;i++) {
            jComboBoxStartDay.addItem(day[i]);
            jComboBoxEndDay.addItem(day[i]);
        }
        
    }
     public boolean isDateSet() {
        
        int year = new Integer(String.valueOf(jComboBoxStartYear.getSelectedItem())).intValue();
        int day = new Integer(String.valueOf(jComboBoxStartDay.getSelectedItem())).intValue();;
        int month = -1;
        String monthString = String.valueOf(jComboBoxStartMonth.getSelectedItem());
        if(monthString.equals("Januar"))    { month = 0; }
        if(monthString.equals("Februar"))   { month = 1; }
        if(monthString.equals("März"))      { month = 2; }
        if(monthString.equals("April"))     { month = 3; }
        if(monthString.equals("Mai"))       { month = 4; }
        if(monthString.equals("Juni"))      { month = 5; }
        if(monthString.equals("Juli"))      { month = 6; }
        if(monthString.equals("August"))    { month = 7; }
        if(monthString.equals("September")) { month = 8; }
        if(monthString.equals("Oktober"))   { month = 9; }
        if(monthString.equals("November"))  { month = 10; }
        if(monthString.equals("Dezember"))  { month = 11; }

        if(!String.valueOf(year).equals("<Bitte wählen>")) {
            if(!String.valueOf(month).equals("<Bitte wählen>")) {
                if(!String.valueOf(day).equals("<Bitte wählen>")) {

                    startDate = ""+year+"-"+month+"-"+day;

                    return true;
                } else {
                    jLabelError.setText("Bitte Tag wählen");
                    return false;
                }
            } else {
                jLabelError.setText("Bitte Monat wählen");
                return false;
            }
        } else {
            jLabelError.setText("Bitte Jahr wählen");
            return false;
        }
    }

    public void newProjectInit() {
        setComboBoxProjectGroup();
    }

    public void editProjectInit() {

    }

    public void getPrGroupID() {
        DB_projektzeit_Connect dbCon = new DB_projektzeit_Connect();
        dbCon.openDB();
        con = dbCon.getCon();
        
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM PrGroup WHERE PrGroup='" + prGroupName + "'";
            ResultSet rst = stmt.executeQuery(sql);

            while(rst.next()) {
                prGroupID = rst.getInt("PrGroupID");
            }
            rst.close();
            stmt.close();
        }
        catch(Exception e) {
            System.out.println(e.toString()); 
            System.exit(1);
        }
        dbCon.closeDB(con);
    }

    public void saveProject() {
    
    }

    public void saveNewProject() {

    }

    /*
     * Alle Projektgruppen in die ComboBox laden
     */
    public void setComboBoxProjectGroup() {

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSaveAndExit;
    private javax.swing.JCheckBox jCheckBoxProjectIsNotActive;
    private javax.swing.JComboBox jComboBoxEndDay;
    private javax.swing.JComboBox jComboBoxEndMonth;
    private javax.swing.JComboBox jComboBoxEndYear;
    private javax.swing.JComboBox jComboBoxPrGroup;
    private javax.swing.JComboBox jComboBoxStartDay;
    private javax.swing.JComboBox jComboBoxStartMonth;
    private javax.swing.JComboBox jComboBoxStartYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JTextField jTextFieldCostLocation;
    private javax.swing.JTextField jTextFieldProject;
    private javax.swing.JTextField jTextFieldTablePos;
    // End of variables declaration//GEN-END:variables
    
}
