/*
 * UserSubGUI.java
 *
 * Created on 21. Dezember 2005, 15:12
 */

package pzm.subgui;

import java.sql.*;
import pzm.dbcon.DB_projektzeit_Connect;
import pzm.core.User;
/**
 *
 * @author  hertel
 */
public class UserSubGUI extends javax.swing.JFrame {
    
    // zeigt an ob Benutzer bearbeitet oder erzeugt werden soll
    private static int status;
    private static String userLogin;
    private User user;
    private Connection con;
    
    
    /** Creates new form UserSubGUI */
    public UserSubGUI(int status, String userLogin) {
        this.status = status;
        this.userLogin = userLogin;
        initComponents();
        if(status == 0) {
            //Neuer Mitarbeiter soll eingefügt werden
            newUserInit();
        }
        if(status == 1) {
            //Mitarbeiter soll bearbeitet werden
            editUserInit();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldOldPass = new javax.swing.JPasswordField();
        jPasswordFieldNewPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldNewPassVerify = new javax.swing.JPasswordField();
        jButtonSaveAndExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stammdaten - Mitarbeiter bearbeiten");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user = getUser();
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 160, -1));

        jLabel1.setText("Vorname");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, -1));

        jLabel2.setText("Nachname");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, -1));
        jPanel1.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 160, -1));

        jLabel3.setText("Benutzername");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel1.add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Passwort ändern");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 320, -1));

        jLabel4.setText("Passwort alt *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        jPanel1.add(jPasswordFieldOldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 160, 20));
        jPanel1.add(jPasswordFieldNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 160, 20));

        jLabel5.setText("neues Passwort");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel6.setText("Passwort wiederholen");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));
        jPanel1.add(jPasswordFieldNewPassVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 160, 20));

        jButtonSaveAndExit.setText("Speichern und Schliessen");
        jButtonSaveAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaveAndExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndExitActionPerformed
        switch(status) {
            case 0:
                newUser();
                setVisible(false);
            case 1:
                editUser();
                setVisible(false);
            default:
                jLabel7.setText("Fehler bei Ausführung des Befehls!");
        }
    }//GEN-LAST:event_jButtonSaveAndExitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSubGUI(status,  userLogin).setVisible(true);
                
            }
        });
    }
    
    public void editUser() {
        String passOld = new String(jPasswordFieldOldPass.getPassword());
        //Überprüfung ob Passwort geändert werden soll
        if(passOld.equals("")) {
            user.setUserName(jTextFieldName.getText());
            user.setUserLastName(jTextFieldLastName.getText());
            user.setUserLogin(jTextFieldLogin.getText());
        }
        else {
            String pass = new String(jPasswordFieldNewPass.getPassword());
            String passVerify = new String(jPasswordFieldNewPassVerify.getPassword());
            //Überprüfung einegebenes 'Altes Passwort' mit Passwort des aktuellen Benutzers übereinstimmt 
            if(passOld.equals(user.getUserPass())) {
                //Überprüfung ob Passwort und Wiederholung übereinstimmen
                if(pass.equals(passVerify)) {
                    user.setUserName(jTextFieldName.getText());
                    user.setUserLastName(jTextFieldLastName.getText());
                    user.setUserLogin(jTextFieldLogin.getText());
                    user.setUserPass(pass);
                }
                else {
                    jLabel7.setText("Passwort und Wiederholung stimmen nicht überein!");
                }
            }
            else {
                jLabel7.setText("'Altes Passwort nicht korrekt'");
            }
            
            
        }
        DB_projektzeit_Connect dbCon = new DB_projektzeit_Connect();
        dbCon.openDB();
        con = dbCon.getCon();
        
        try {
            Statement stmt = con.createStatement();
            String sql = "UPDATE User SET Name='" + user.getUserName() + "', " +
                                           "LastName='" + user.getUserLastName() + "', " + 
                                           "Login='" + user.getUserLogin() + "', " +
                                           "Pass='" + user.getUserPass() + "' " + 
                        "WHERE Login='" + user.getUserLogin() + "'";
            stmt.executeUpdate(sql);
            stmt.close();
        }
        catch(Exception e) {
            System.out.println(e.toString()); 
            System.exit(1); 
        }
        dbCon.closeDB(con); 
        
        //UPDATE Person SET Name = 'user.getName()', LastName = 'user.getLastName()', Login = 'user.getLogin()',
        //                  Pass = 'user.getUserPass()'
        //WHERE Login = 'userLogin'
    }
    
    public void newUser() {
        user.setUserName(jTextFieldName.getText());
        user.setUserLastName(jTextFieldLastName.getText());
        user.setUserLogin(jTextFieldLogin.getText());
        String pass = new String(jPasswordFieldNewPass.getPassword());
        String passVerify = new String(jPasswordFieldNewPassVerify.getPassword());
        if(pass.equals(passVerify)) {
            user.setUserPass(pass);
        }
        else {
            jLabel7.setForeground(new java.awt.Color(255, 0, 0));
            jLabel7.setText("Passwörter stimmen nicht überein!");
        }
        DB_projektzeit_Connect dbCon = new DB_projektzeit_Connect();
        dbCon.openDB();
        con = dbCon.getCon();
        
        try {
            Statement stmt = con.createStatement();
            String sql = "INSERT INTO User (Name, LastName, Login, Pass)" +
                         "VALUES ('" + user.getUserName() + "', '" + user.getUserLastName() + 
                         "', '" + user.getUserLogin()+ "', '" + user.getUserPass() + "')";
            stmt.executeUpdate(sql);
            stmt.close();
        }
        catch(Exception e) {
            System.out.println(e.toString()); 
            System.exit(1); 
        }
        dbCon.closeDB(con); 
    }
    
    //Design der GUI wird angepasst für Aktion 'Aktuellen Mitarbeiter bearbeiten'
    public void editUserInit() {
        jTextFieldName.setText(user.getUserName());
        jTextFieldLastName.setText(user.getUserLastName());
        jTextFieldLogin.setText(user.getUserLogin());
        jTextFieldLogin.setEditable(false);
        jTextFieldLogin.setToolTipText("Der Benutzername darf nicht geändert werden!");
    }
    
    //Design der GUI wird angepasst für Aktion 'Neuen Mitarbeiter einfügen'
    public void newUserInit() {
        jLabel4.setVisible(false);
        jPasswordFieldOldPass.setVisible(false);
        jLabel7.setText("Passwort eingeben");
    }
    
    public User getUser() {
        User user = new User("","","","");
        DB_projektzeit_Connect dbCon = new DB_projektzeit_Connect();
        dbCon.openDB();
        con = dbCon.getCon();
        
        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM User WHERE Login = '" + userLogin + "'";
            ResultSet rst = stmt.executeQuery(sql);

            while(rst.next()) {
                user.setUserName(rst.getString("Name"));
                user.setUserLastName(rst.getString("LastName"));
                user.setUserPass(rst.getString("Pass"));
            }
            rst.close();
            stmt.close();
        }
        catch(Exception e) {
            System.out.println(e.toString()); 
            System.exit(1); 
        }
        dbCon.closeDB(con); 
        user.setUserLogin(userLogin);
        return user;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveAndExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldNewPass;
    private javax.swing.JPasswordField jPasswordFieldNewPassVerify;
    private javax.swing.JPasswordField jPasswordFieldOldPass;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
    
}
