package pzm.gui;

import de.wannawork.jcalendar.*;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*; 
import java.util.Vector;
import java.util.Calendar;
import java.util.Properties;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import java.util.Enumeration;
import java.util.StringTokenizer;
import java.awt.Rectangle;
import java.awt.Dimension;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.text.DateFormat;
import java.util.Locale;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.table.TableColumnModel;
import pzm.tablemodel.ColumnHeaderToolTips;
import pzm.tablemodel.MainTableModel;
import pzm.core.User;
import pzm.core.Term;
import pzm.core.Project;
import pzm.tablemodel.VerticalTableHeaderCellRenderer;
import pzm.dbcon.DB_projektzeit_Connect;
import pzm.gui.TermGUI;
//import pzm.tablemodel.MultiLineHeaderRenderer;


/*
 * MainGUI.java
 *
 * Created on 13. Dezember 2005, 13:04
 */

/**
 *
 * @author  hertel
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static Connection con;
    private static LoginGUI logGUI;
    private static MainGUI mainGUI;
    private static Vector columnNames = new Vector();
    private static Vector data = new Vector();
    private static String winClassName = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    public static User activeUser = new User("","","");
    private Term actTerm = new Term(0,0,0);
    private Project project = new Project(0,"","",0);
    ColumnHeaderToolTips tips = new ColumnHeaderToolTips();
    private Calendar cal;
    public static final Properties applicationProperties = new Properties();

   
    /** Creates new form MainGUI */
    public MainGUI() {
        initComponents();
        centerScreen();
        //setCalendarChooser();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNewTerm = new javax.swing.JButton();
        jButtonEditTerm = new javax.swing.JButton();
        calendarComboBox = new de.wannawork.jcalendar.JCalendarComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        AuswertungMenu = new javax.swing.JMenu();
        yearMenuItem2006 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        StammdatenMenu = new javax.swing.JMenu();
        projectsMenuItem = new javax.swing.JMenuItem();
        UserMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProjektZeitenManager");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 725));
        setName("Projektzeitenmanager"); // NOI18N
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonNewTerm.setText("Zeiteintrag");
        jButtonNewTerm.setToolTipText("Neuen Zeiteintrag erstellen");
        jButtonNewTerm.setEnabled(false);
        jButtonNewTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewTermActionPerformed(evt);
            }
        });

        jButtonEditTerm.setText("Bearbeiten");
        jButtonEditTerm.setEnabled(false);
        jButtonEditTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditTermActionPerformed(evt);
            }
        });

        calendarComboBox.setMinimumSize(new java.awt.Dimension(0, 0));
        calendarComboBox.setPreferredSize(new java.awt.Dimension(130, 16));
        calendarComboBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                calendarComboBoxStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonNewTerm)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonEditTerm)
                .add(30, 30, 30)
                .add(calendarComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(650, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(calendarComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButtonNewTerm)
                        .add(jButtonEditTerm)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 0));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fileMenu.setBorder(null);
        fileMenu.setText("Datei");

        exitMenuItem.setText("Beenden");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        cutMenuItem.setText("Cut");
        cutMenuItem.setEnabled(false);
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy");
        copyMenuItem.setEnabled(false);
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        pasteMenuItem.setEnabled(false);
        editMenu.add(pasteMenuItem);

        menuBar.add(editMenu);

        AuswertungMenu.setText("Auswertung");

        yearMenuItem2006.setText("Jahresauswertung");
        yearMenuItem2006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearMenuItem2006ActionPerformed(evt);
            }
        });
        AuswertungMenu.add(yearMenuItem2006);

        jMenuItem1.setText("Projekt");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        AuswertungMenu.add(jMenuItem1);

        menuBar.add(AuswertungMenu);

        StammdatenMenu.setText("Stammdaten");

        projectsMenuItem.setText("Projekte");
        projectsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectsMenuItemActionPerformed(evt);
            }
        });
        StammdatenMenu.add(projectsMenuItem);

        UserMenuItem.setText("Mitarbeiter");
        UserMenuItem.setActionCommand("Mitarbeiter");
        UserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMenuItemActionPerformed(evt);
            }
        });
        StammdatenMenu.add(UserMenuItem);

        menuBar.add(StammdatenMenu);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projectsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectsMenuItemActionPerformed
    //ProjectGUI öffnen um alle Projekte anzuzeigen
        ProjectGUI projectWindow = new ProjectGUI();
        projectWindow.setVisible(true);
    }//GEN-LAST:event_projectsMenuItemActionPerformed

    private void yearMenuItem2006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearMenuItem2006ActionPerformed
    // TotalGUI öffnen um alle Zeiteinträge des Jarhres anzuzeigen
        int year = calendarComboBox.getCalendar().get(Calendar.YEAR);
        TotalGUI totalWindow = new TotalGUI(year);
        totalWindow.setVisible(true);
    }//GEN-LAST:event_yearMenuItem2006ActionPerformed

    private void jButtonEditTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditTermActionPerformed
        if(table.getSelectedColumn() != -1) {
            cal = Calendar.getInstance();
            cal.set(calendarComboBox.getCalendar().get(Calendar.YEAR),
                    calendarComboBox.getCalendar().get(Calendar.MONTH),
                    table.getSelectedRow()+1);
            project.setProject(table.getModel().getColumnName(table.getSelectedColumn()));
            project.setProjYear(calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().YEAR));
            TermEditGUI termEditGUI = new TermEditGUI(actTerm, activeUser, cal, project);
            termEditGUI.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditTermActionPerformed
    
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(!activeUser.getUserLogin().equals("")) {
            table.setModel(new MainTableModel(activeUser.getUserID(), calendarComboBox.getCalendar()));
            TableCellRenderer headerRenderer = new VerticalTableHeaderCellRenderer();
            Enumeration tabColumns = table.getColumnModel().getColumns();
            while (tabColumns.hasMoreElements()) {
                TableColumn col = (TableColumn) tabColumns.nextElement();
                col.setHeaderRenderer(headerRenderer);
            }
            //this.table.getTableHeader().setDefaultRenderer(new MultiLineHeaderRenderer());
            // Tooltips für Tabellenköpfe erzeugen
/*            JTableHeader header = table.getTableHeader();
            for (int c=0; c<table.getColumnCount(); c++) {
                TableColumn col = table.getColumnModel().getColumn(c);
                tips.setToolTip(col, table.getColumnName(c));
            }
            header.addMouseMotionListener(tips);
*/           
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButtonNewTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewTermActionPerformed
        if(table.getSelectedRow() == -1) {
            project.setProject(table.getColumnName(table.getSelectedColumn()));
            cal = Calendar.getInstance();
            cal.set(calendarComboBox.getCalendar().get(Calendar.YEAR), calendarComboBox.getCalendar().get(Calendar.MONTH),
                    table.getSelectedRow()+1);
            project.setProjYear(calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().YEAR));
            TermGUI termWin = new TermGUI(1, actTerm, activeUser, cal, project);
            termWin.setVisible(true);
        }
        else {
            cal = Calendar.getInstance();
            cal.set(calendarComboBox.getCalendar().get(Calendar.YEAR), calendarComboBox.getCalendar().get(Calendar.MONTH),
                    table.getSelectedRow()+1);
            project.setProjYear(calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().YEAR));
            TermGUI termWinSel = new TermGUI(1, actTerm, activeUser, cal, project);
            termWinSel.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonNewTermActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void UserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserMenuItemActionPerformed
    // UserGUI öffnen um alle Mitarbeiter anzuzeigen
        UserGUI userWindow = new UserGUI();
        userWindow.setVisible(true);
    }//GEN-LAST:event_UserMenuItemActionPerformed
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if(evt.getClickCount() == 2) {
            cal = Calendar.getInstance();
            cal.set(calendarComboBox.getCalendar().get(Calendar.YEAR), calendarComboBox.getCalendar().get(Calendar.MONTH),
                    table.getSelectedRow()+1);

            if(getNumberOfTermsForDate(cal, activeUser.getUserID()) == 1) {
                editTerm(activeUser.getUserLogin(), cal); //falls bereits ein Termin eingetragen wurde: editieren
            } else {
                if(getNumberOfTermsForDate(cal, activeUser.getUserID()) > 1) {
                    // alte version erlaubte mehrere Einträge pro Tag und Projekt, daher muss der richtige Eintrag ausgewählt werden
                    project.setProjYear(calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().YEAR));
                    TermEditGUI termEditGUI = new TermEditGUI(actTerm, activeUser, cal, project);
                    termEditGUI.setVisible(true);
                } else {
                    createNewTerm(activeUser.getUserLogin()); //sonst: neu eintragen
                }
            }
        }
}//GEN-LAST:event_tableMouseClicked

    private void calendarComboBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_calendarComboBoxStateChanged
        if(evt.getSource() == calendarComboBox) {
            int year = calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().YEAR);
            int month = calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().MONTH);
            int date = calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().DAY_OF_MONTH);
            System.out.println("neues Dat: " + date + "." + month + "." + year);
            cal = Calendar.getInstance();
            cal.set(year, month, date+1);
            table.setModel(new MainTableModel(activeUser.getUserID(), calendarComboBox.getCalendar()));
            TableCellRenderer headerRenderer = new VerticalTableHeaderCellRenderer();
            Enumeration tabColumns = table.getColumnModel().getColumns();
            while (tabColumns.hasMoreElements()) {
                TableColumn col = (TableColumn) tabColumns.nextElement();
                col.setHeaderRenderer(headerRenderer);
            }
        }
    }//GEN-LAST:event_calendarComboBoxStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try
		{
			File file = new File("E:\\Konzept-e\\sven\\pzm\\PZMSettings.xml");
			if(!file.exists())
			{
                            file = new File("C:\\Users\\user\\konzept-e\\Projekte\\pzm-application\\PZMSettings.xml");
                            //file = new File("R:\\PZM\\config\\PZMSettings.xml");
			}
			
			FileInputStream inputStream = new FileInputStream(file);
			applicationProperties.loadFromXML(inputStream);
			inputStream.close();

		} catch (Exception ex)
		{
			Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(mainGUI, "Die Datei 'PZMSettings.xml' konnte "
					+ "nicht gefunden werden oder es trat ein Fehler beim Laden auf!\n"
					+ "Bitte überprüfen Sie, ob die Datei vorhanden ist und starten Sie "
					+ "die Anwendung dann erneut.", "Fehler", JOptionPane.ERROR_MESSAGE);
			System.exit(1);
		}

		try
		{
			Logger logger = Logger.getLogger(MainGUI.class.getName());

			FileHandler fh = new FileHandler(applicationProperties.getProperty("LoggerLogfilePath"), true);
			logger.addHandler(fh);
			logger.setLevel(Level.ALL);
			SimpleFormatter formatter = new SimpleFormatter();
			fh.setFormatter(formatter);

			logger.log(Level.INFO, "PZM erfolgreich gestartet und initialisiert.");

		} catch (Exception ex)
		{
			Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(mainGUI, "Die Anwendung konnte die Datei zur "
					+ "Ausgabe von Fehlermeldungen nicht öffnen.\n\nBitte informieren Sie Ihren "
					+ "Administrator über diese Fehlermeldung oder starten Sie die Anwendung erneut.");
			System.exit(1);
		}

		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				setLookAndFeel();
				mainGUI = new MainGUI();
				mainGUI.setVisible(false);

                                LoginGUI logGUI = new LoginGUI(mainGUI, true);
                                logGUI.setVisible(true);
                        }
		});

    }

    /**
     * @param cal Calender with chosen date
     * @param userID id of user who is logged in
     */
    public int getNumberOfTermsForDate(Calendar cal, int userID) {
        DB_projektzeit_Connect dbCon = new DB_projektzeit_Connect();
        dbCon.openDB();
        con = dbCon.getCon();
        int termCount = 0;

        try {
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM Term LEFT JOIN Project ON Term.ProjectID=Project.ProjectID " +
                         "WHERE Term.UserID=" + userID + " AND Term.TermDate LIKE '" + 
                         cal.get(Calendar.DATE) + "." + (cal.get(Calendar.MONTH)+1) + "." + cal.get(Calendar.YEAR) +
                         "' AND Project.Project='" + table.getColumnName(table.getSelectedColumn()) + "' AND Project.notActive=0";
            ResultSet rst = stmt.executeQuery(sql);

            while(rst.next()) {
                termCount = termCount + 1;
                actTerm.setDuration(rst.getInt("Duration"));
                actTerm.setTermID(rst.getInt("TermID"));
                actTerm.setProjectID(rst.getInt("ProjectID"));
            }
            rst.close();
            stmt.close();
        }
        catch(Exception e) {
            System.out.println(e.toString());
            System.exit(1);
        }
        dbCon.closeDB(con);
        return termCount;
    }

    public void editTerm(String userLogin, Calendar cal) {
        if(table.getSelectedRow() != -1) {
            project.setProject(table.getModel().getColumnName(table.getSelectedColumn()));
            project.setProjYear(cal.YEAR);
            TermGUI tGUI = new TermGUI(0, actTerm, activeUser, cal, project);
            tGUI.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public void createNewTerm(String userLogin) {
        project.setProject(table.getModel().getColumnName(table.getSelectedColumn()));
        project.setProjYear(calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().YEAR));
        TermGUI termWinSel = new TermGUI(1, actTerm, activeUser, cal, project);
        termWinSel.setVisible(true);
    }

    public int getMinutesOfTimeString(String duration) {
        int hours = 0;
        int minutes = 0;
        StringTokenizer tokenizer = new StringTokenizer(duration,":");
        while(tokenizer.hasMoreTokens()) {
            if(tokenizer.countTokens() == 2) {
                hours = (Integer.valueOf(tokenizer.nextToken()).intValue()) * 60;
            }
            else if(tokenizer.countTokens() == 1) {
                minutes = (Integer.valueOf(tokenizer.nextToken()).intValue());
            }
        }
        return hours + minutes;
    }

    public void setActiveUser(String login, int userID) {
        this.activeUser.setUserLogin(login);
        this.activeUser.setUserID(userID);
    }
    
    public static void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel(winClassName);
        } catch(Exception e) {
            System.out.println(e.toString()); 
            System.exit(1); 
        }
    }

    public void centerScreen() {
        Dimension dim = getToolkit().getScreenSize();
        Rectangle abounds = getBounds();
        setLocation((dim.width - abounds.width) / 2,
        (dim.height - abounds.height) / 2);
        super.setVisible(true);
        requestFocus();
    }

    /*
     * da es keine Aktivitaäten mehr gibt, kann nur noch ein Term pro Tag eigetragen werden
     *
     public void openTermEditWindow() {
        int year = calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().YEAR);
        int month = calendarComboBox.getCalendar().get(calendarComboBox.getCalendar().MONTH);
        int date = table.getSelectedRow();
        cal = Calendar.getInstance();
        cal.set(year, month, date+1);
        TermEditGUI termWinSel = new TermEditGUI(activeUser.getUserID(), activeUser.getUserLogin(),
                cal, table.getModel().getColumnName(table.getSelectedColumn()));
        termWinSel.setVisible(true);
    }
     *
     *
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AuswertungMenu;
    private javax.swing.JMenu StammdatenMenu;
    private javax.swing.JMenuItem UserMenuItem;
    private de.wannawork.jcalendar.JCalendarComboBox calendarComboBox;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButtonEditTerm;
    private javax.swing.JButton jButtonNewTerm;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem projectsMenuItem;
    private javax.swing.JTable table;
    private javax.swing.JMenuItem yearMenuItem2006;
    // End of variables declaration//GEN-END:variables
    
}
