/*
 * PrGroupGUI.java
 *
 * Created on 20. Dezember 2005, 12:04
 */

package pzm.gui;

/**
 *
 * @author  hertel
 */
public class PrGroupGUI extends javax.swing.JFrame {
    
    /** Creates new form PrGroupGUI */
    public PrGroupGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jListPrGroup = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jButtonNewPrGroup = new javax.swing.JButton();
        jButtonDeletePrGroup = new javax.swing.JButton();
        jButtonEditPrGroup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stammdaten - Projektgruppen");
        setName("PrGroupWindow"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jListPrGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 578, 450));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNewPrGroup.setText("Neu");
        jButtonNewPrGroup.setToolTipText("Neue Projektgruppe erstellen");
        jPanel1.add(jButtonNewPrGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jButtonDeletePrGroup.setText("Löschen");
        jButtonDeletePrGroup.setToolTipText("<HTML>Selektierte Projektgruppe löschen.<BR>!ACHTUNG!<BR> Alle der Projektgruppe zugeordneten Projekte werden ebenfalls gelöscht.</HTML>");
        jPanel1.add(jButtonDeletePrGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 80, -1));

        jButtonEditPrGroup.setText("Bearbeiten");
        jButtonEditPrGroup.setToolTipText("Selektierte Projektgruppe bearbeiten");
        jPanel1.add(jButtonEditPrGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrGroupGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeletePrGroup;
    private javax.swing.JButton jButtonEditPrGroup;
    private javax.swing.JButton jButtonNewPrGroup;
    private javax.swing.JList jListPrGroup;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
