/*
 * ProjectGUI.java
 *
 * Created on 1. Januar 2006, 22:26
 */

package pzm.gui;

import pzm.tablemodel.ProjectsTableModel;
import pzm.subgui.ProjectSubGUI;
/**
 *
 * @author  hertel
 */
public class ProjectGUI extends javax.swing.JFrame {

    public static ProjectGUI projGUI = new ProjectGUI();
    /** Creates new form ProjectGUI */
    public ProjectGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjects = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonDe_ActivateProject = new javax.swing.JButton();
        jButtonEditProject = new javax.swing.JButton();
        jButtonNewProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stammdaten - Projekte");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 0));

        jTableProjects.setModel(new ProjectsTableModel()
        );
        jTableProjects.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableProjects);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDe_ActivateProject.setText("(de-)aktivieren");
        jButtonDe_ActivateProject.setToolTipText("Das gewählte Projekt aktivieren oder deaktivieren");
        jButtonDe_ActivateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDe_ActivateProjectActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDe_ActivateProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jButtonEditProject.setText("Bearbeiten");
        jButtonEditProject.setToolTipText("Das gewählte Projekt aktivieren");
        jButtonEditProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditProjectActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jButtonNewProject.setText("Neu");
        jButtonNewProject.setToolTipText("Neues Projekt erstellen");
        jButtonNewProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewProjectActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Öffnet das Formular ProjectSubGUI um neues Projekt anzulegen
     */
    private void jButtonNewProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewProjectActionPerformed
        ProjectSubGUI newProject = new ProjectSubGUI(0);
        newProject.setVisible(true);
    }//GEN-LAST:event_jButtonNewProjectActionPerformed

    /*
     *  Öffnet das Formular ProjectSubGUI um ein bestehendes, aus der Tabelle gewähltes Projekt zu bearbeiten
     */
    private void jButtonEditProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditProjectActionPerformed
        if(jTableProjects.getSelectedRow() != -1) {
            Object project = jTableProjects.getValueAt(jTableProjects.getSelectedRow(), 0);
            Object projectID = jTableProjects.getValueAt(jTableProjects.getSelectedRow(), 4);
            if(project != null) {
            ProjectSubGUI editProject = new ProjectSubGUI(1, String.valueOf(project), (Integer)projectID);
            editProject.setVisible(true);
            projGUI.setVisible(false);
           }
        }
    }//GEN-LAST:event_jButtonEditProjectActionPerformed

    /*
     *  De-/reaktiviert das in der Tabelle gewählte Projekt und lädt das TableModel neu
     */
    private void jButtonDe_ActivateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDe_ActivateProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDe_ActivateProjectActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                projGUI.setVisible(true);
            }
        });
    }
    
    /*
     *BEIM EINTRAGEN VON PROJEKTEN BEACHTEN DAS NICHT MEHR ALS 100 PROJEKTE
     *ANGEZEIGT WERDEN KÖNNEN - Beschränkung in ProjectsTableModel
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDe_ActivateProject;
    private javax.swing.JButton jButtonEditProject;
    private javax.swing.JButton jButtonNewProject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjects;
    // End of variables declaration//GEN-END:variables
    
}
