/*
 * UserGUI.java
 *
 * Created on 20. Dezember 2005, 12:44
 */

package pzm.gui;

import pzm.dialog.DeleteUserDialog;
import pzm.subgui.UserSubGUI;
import pzm.tablemodel.UserTableModel;
import java.sql.*;
import java.awt.event.*;
import java.awt.event.WindowAdapter.*;

/**
 *
 * @author  hertel
 */
public class UserGUI extends javax.swing.JFrame  {
    
    
    public static UserGUI userWin = new UserGUI();
    private static Connection con;
    /** Creates new form UserGUI */
    public UserGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNewUser = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jButtonEditUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stammdaten - Mitarbeiter");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNewUser.setText("Neu");
        jButtonNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButtonDeleteUser.setText("Löschen");
        jButtonDeleteUser.setEnabled(false);
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jButtonEditUser.setText("Bearbeiten");
        jButtonEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setMinimumSize(new java.awt.Dimension(0, 0));

        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setModel(new UserTableModel());
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 460, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 362, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(evt.WINDOW_GAINED_FOCUS != 1) {
            table.setModel(new UserTableModel());
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButtonEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditUserActionPerformed
        if(table.getSelectedRow() != -1) {
            Object login = table.getValueAt(table.getSelectedRow(), 2);
            if(login != null) {
            UserSubGUI newUser = new UserSubGUI(1, String.valueOf(login));
            newUser.setVisible(true);
            userWin.setVisible(false);
            //Benutzername des Benutzers welcher aktuell bearbeitet wird

            }
        }
    }//GEN-LAST:event_jButtonEditUserActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        if(table.getSelectedRow() != -1) {
            Object login = table.getValueAt(table.getSelectedRow(), 2);
            if(login != null) {
                //@TODO: User und alle entsprechenden Zeiteinträge auf deaktivieren setzen
                //
                //DeleteUserDialog deleteUser = new DeleteUserDialog(userWin, true, String.valueOf(login));
            //deleteUser.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewUserActionPerformed
        Object login = 0;
        UserSubGUI newUser = new UserSubGUI(0, String.valueOf(login));
        newUser.setVisible(true);
    }//GEN-LAST:event_jButtonNewUserActionPerformed

    private void actionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionMouseClicked
        if(evt.getClickCount() == 2) {
            onDoubleClick();
        }
    }//GEN-LAST:event_actionMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                userWin.setVisible(true);
            }
        });
    }
    
    public static void onDoubleClick() {
        userWin.setVisible(false);
        /*
         * Neues Fenster öffnen 
         *
         */
        userWin.setVisible(true);
    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonEditUser;
    private javax.swing.JButton jButtonNewUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    
}




